# Generated by Django 4.2.4 on 2023-09-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='%Y/%m/%d/'),
        ),
    ]
